apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.app.prefix }}-app
  name: {{ .Values.app.prefix }}-app
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: {{ .Values.service.authproxy.name }}
    port: {{ .Values.service.authproxy.port }}
    targetPort: {{ .Values.service.authproxy.targetPort }}
  - name: {{ .Values.service.camunda.name }}
    port: {{ .Values.service.camunda.port }}
    targetPort: {{ .Values.service.camunda.targetPort }}
  - name: {{ .Values.service.security.name }}
    port: {{ .Values.service.security.port }}
    targetPort: {{ .Values.service.security.targetPort }}
  - name: {{ .Values.service.admin.name }}
    port: {{ .Values.service.admin.port }}
    targetPort: {{ .Values.service.admin.targetPort }}
  - name: {{ .Values.service.systementry.name }}
    port: {{ .Values.service.systementry.port }}
    targetPort: {{ .Values.service.systementry.targetPort }}

  - name: {{ .Values.service.test1.name }}
    port: {{ .Values.service.test1.port }}
    targetPort: {{ .Values.service.test1.targetPort }}

  - name: {{ .Values.service.test2.name }}
    port: {{ .Values.service.test2.port }}
    targetPort: {{ .Values.service.test2.targetPort }}

  - name: {{ .Values.service.test3.name }}
    port: {{ .Values.service.test3.port }}
    targetPort: {{ .Values.service.test3.targetPort }}

  - name: {{ .Values.service.test4.name }}
    port: {{ .Values.service.test4.port }}
    targetPort: {{ .Values.service.test4.targetPort }}

  - name: {{ .Values.service.gepitemtagsmanager.name }}
    port: {{ .Values.service.gepitemtagsmanager.port }}
    targetPort: {{ .Values.service.gepitemtagsmanager.targetPort }}

  - name: {{ .Values.service.test6.name }}
    port: {{ .Values.service.test6.port }}
    targetPort: {{ .Values.service.test6.targetPort }}

  - name: {{ .Values.service.test7.name }}
    port: {{ .Values.service.test7.port }}
    targetPort: {{ .Values.service.test7.targetPort }}

  - name: {{ .Values.service.test8.name }}
    port: {{ .Values.service.test8.port }}
    targetPort: {{ .Values.service.test8.targetPort }}

  - name: {{ .Values.service.test9.name }}
    port: {{ .Values.service.test9.port }}
    targetPort: {{ .Values.service.test9.targetPort }}

  - name: {{ .Values.service.test10.name }}
    port: {{ .Values.service.test10.port }}
    targetPort: {{ .Values.service.test10.targetPort }}

  - name: {{ .Values.service.test11.name }}
    port: {{ .Values.service.test11.port }}
    targetPort: {{ .Values.service.test11.targetPort }}

  selector:
    name: {{ .Values.app.prefix }}-app