apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.prefix }}-app
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.app.prefix }}-app
  template:
    metadata:
      labels:
        name: {{ .Values.app.prefix }}-app
    spec:
      containers:
        - name: {{ .Values.deployment.authproxy.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.authproxy.image }}
          ports:
            - name: http-port
              containerPort: 8001
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"
            - name: CAMUNDAURL
              value: "http://{{ .Values.app.prefix }}-app.{{ .Values.app.prefix }}.svc.cluster.local:8002"          
        - name: {{ .Values.deployment.camunda.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.camunda.image }}
          ports:
            - name: http-port
              containerPort: 8002
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"
            - name: CAMUNDAPOD_URL
              value: "http://{{ .Values.app.prefix }}-camunda-pod.{{ .Values.app.prefix }}.svc.cluster.local:8080"
            # - name: VAULT_API
            #   value: "http://vault.{{ .Values.app.namespace }}.svc.cluster.local:8200"
        - name: {{ .Values.deployment.admin.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.admin.image }}
          ports:
            - name: http-port
              containerPort: 8004
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            # - name: VAULT_API
            #   value: "http://vault.{{ .Values.app.namespace }}.svc.cluster.local:8200"    
        - name: {{ .Values.deployment.security.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.security.image }}
          ports:
            - name: http-port
              containerPort: 8003
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"
        - name: {{ .Values.deployment.systementry.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.systementry.image }}
          ports:
            - name: http-port
              containerPort: 8016
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test1.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test1.image }}
          ports:
            - name: http-port
              containerPort: 8017
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test2.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test2.image }}
          ports:
            - name: http-port
              containerPort: 8018
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test3.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test3.image }}
          ports:
            - name: http-port
              containerPort: 8019
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test4.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test4.image }}
          ports:
            - name: http-port
              containerPort: 8020
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.gepitemtagsmanager.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.gepitemtagsmanager.image }}
          ports:
            - name: http-port
              containerPort: 8006
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test6.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test6.image }}
          ports:
            - name: http-port
              containerPort: 8022
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test7.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test7.image }}
          ports:
            - name: http-port
              containerPort: 8023
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test8.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test8.image }}
          ports:
            - name: http-port
              containerPort: 8024
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test9.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test9.image }}
          ports:
            - name: http-port
              containerPort: 8025
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test10.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test10.image }}
          ports:
            - name: http-port
              containerPort: 8026
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"

        - name: {{ .Values.deployment.test11.name }}-container
          imagePullPolicy: {{ .Values.deployment.defaultImagePullPolicy }}
          image: {{ .Values.deployment.test11.image }}
          ports:
            - name: http-port
              containerPort: 8027
          env:
            - name: {{ .Values.app.prefix }}-app-db
              value: {{ .Values.app.prefix }}-app-db
            - name: MONGO_DB_URL
              value: "mongodb://{{ .Values.app.prefix }}-app-db.{{ .Values.app.prefix }}.svc.cluster.local:27017/{{ .Values.app.prefix }}"
