# Default values for fargatepoc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  prefix: fargatepoc
  namespace: fargatepoc

service:
  type: NodePort
  appbuilderType: NodePort

  apigateway:
    name: apigateway
    type: NodePort
    port: 8000  
    targetPort: 8000
    nodePort: 31234
  camunda:
    name: camunda
    type: NodePort
    port: 8002
    targetPort: 8002
  authproxy:
    name: authproxy
    type: NodePort
    port: 8001
    targetPort: 8001
  security:
    name: securitymanager
    type: NodePort
    port: 8003
    targetPort: 8003
  admin:
    name: adminmanager
    type: NodePort
    port: 8004
    targetPort: 8004
  mongo:
    name: mongo
    type: NodePort
    port: 27017
    targetPort: 27017
  desktop:
    name: desktop
    type: NodePort
    port: 5000
    targetPort: 5000
  camundapod:
    name: camundapod
    type: NodePort
    port: 8080
    targetPort: 8080
  systementry: 
    name: systementry
    type: NodePort
    port: 8016
    targetPort: 8016

  test1: 
    name: test1
    type: NodePort
    port: 8017
    targetPort: 8017

  test2: 
    name: test2
    type: NodePort
    port: 8018
    targetPort: 8018

  test3: 
    name: test3
    type: NodePort
    port: 8019
    targetPort: 8019

  test4: 
    name: test4
    type: NodePort
    port: 8020
    targetPort: 8020

  gepitemtagsmanager: 
    name: gepitemtagsmanager
    type: NodePort
    port: 8006
    targetPort: 8006

  test6: 
    name: test6
    type: NodePort
    port: 8022
    targetPort: 8022

  test7: 
    name: test7
    type: NodePort
    port: 8023
    targetPort: 8023

  test8: 
    name: test8
    type: NodePort
    port: 8024
    targetPort: 8024

  test9: 
    name: test9
    type: NodePort
    port: 8025
    targetPort: 8025

  test10: 
    name: test10
    type: NodePort
    port: 8026
    targetPort: 8026

  test11: 
    name: test11
    type: NodePort
    port: 8027
    targetPort: 8027


deployment:
  defaultImagePullPolicy: IfNotPresent
  customImagePullPolicy: Always
  apigateway:
     name: apigateway
     image: geppettotest/fargatepoc-apigateway:1.0
  mongo:
     name: mongo
     image: mongo:3.2   
  camunda:
     name: camunda
     image: geppettodistribution/default-camunda:2.0
  authproxy:
     name: authproxy
     image: geppettodistribution/default-authproxy:2.0
  security:
     name: securitymanager
     image: geppettodistribution/default-securitymanager:2.0
  admin:
     name: adminmanager
     image: geppettodistribution/default-adminmanager:2.0
  desktop:
     name: desktop
     image: geppettotest/fargatepoc-desktop:1.0
  systementry: 
    name: systementry
    image: geppettotest/fargatepoc-systementry:1.0

  test1: 
    name: test1
    image: geppettotest/fargatepoc-test1:1.0

  test2: 
    name: test2
    image: geppettotest/fargatepoc-test2:1.0

  test3: 
    name: test3
    image: geppettotest/fargatepoc-test3:1.0

  test4: 
    name: test4
    image: geppettotest/fargatepoc-test4:1.0

  gepitemtagsmanager: 
    name: gepitemtagsmanager
    image: geppettotest/fargatepoc-gepitemtagsmanager:1.0

  test6: 
    name: test6
    image: geppettotest/fargatepoc-test6:1.0

  test7: 
    name: test7
    image: geppettotest/fargatepoc-test7:1.0

  test8: 
    name: test8
    image: geppettotest/fargatepoc-test8:1.0

  test9: 
    name: test9
    image: geppettotest/fargatepoc-test9:1.0

  test10: 
    name: test10
    image: geppettotest/fargatepoc-test10:1.0

  test11: 
    name: test11
    image: geppettotest/fargatepoc-test11:1.0

  camundapod:
     name: camundapod
     image: geppettodistribution/camunda-local:Jan2021

config:
  vault:
    rootToken: vault-fargatepoc-2021

persistentVolume:
  mongo:
    storage: 5Gi  

persistentVolumeClaim:
  mongo:
    storage: 5Gi

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}